# 端口
server:
    port: 9003

# sa-token配置 
sa-token:
    # 打印操作日志
    is-log: true

    # sso-client 相关配置
    sso-client:
        # 应用标识
        client: sso-client3
        # sso-server 端主机地址
        server-url: http://sa-sso-server.com:9000
        # 在 sso-server 端前后端分离时需要单独配置 auth-url 参数（上面的不要注释，auth-url 配置项和 server-url 要同时存在）
        # auth-url: http://127.0.0.1:8848/sa-token-demo-sso-server-h5/sso-auth.html
        # 使用 Http 请求校验 ticket (模式三)
        is-http: true
        # API 接口调用秘钥
        secret-key: SSO-C3-kQwIOrYvnXmSDkwEiFngrKidMcdrgKor

# 配置 Sa-Token Dao（此处与SSO-Server端连接不同的Redis）
sa-token.dao: #名字可以随意取
    redis:
        server: "localhost:6379"
#        password: 123456
        db: 4
        maxTotal: 200

        