# 端口
server:
    port: 9000

# Sa-Token 配置
sa-token:
    # 打印操作日志
    is-log: true

    # SSO 模式一配置  (非模式一不需要配置)
#    cookie:
#        # 配置 Cookie 作用域
#        domain: stp.com

    # SSO-Server 配置
    sso-server:
        # Ticket有效期 (单位: 秒)，默认五分钟
        ticket-timeout: 300
        # 主页路由：在 /sso/auth 登录页不指定 redirect 参数时，默认跳转的地址
        home-route: /home
        # 是否启用匿名 client (开启匿名 client 后，允许客户端接入时不提交 client 参数)
        allow-anon-client: true
        # 所有允许的授权回调地址 (匿名 client 使用)
        allow-url: "*"
        # API 接口调用秘钥 (全局默认 + 匿名 client 使用)
        secret-key: kQwIOrYvnXmSDkwEiFngrKidMcdrgKor
        # 应用列表：配置接入的应用信息
        clients:
            # 应用 sso-client1：采用模式一对接 (同域、同Redis)
            sso-client1:
                client: sso-client1
                allowUrl: "*"
            # 应用 sso-client2：采用模式二对接 (跨域、同Redis)
            sso-client2:
                client: sso-client2
                allowUrl: "*"
                secretKey: SSO-C2-kQwIOrYvnXmSDkwEiFngrKidMcdrgKor
            # 应用 sso-client3：采用模式三对接 (跨域、跨Redis)
            sso-client3:
                # 应用名称
                client: sso-client3
                # 允许授权地址
                allowUrl: "*"
                # 是否接收消息推送
                isPush: true
                # 消息推送地址
                pushUrl: http://sa-sso-client1.com:9003/sso/pushC
                # 接口调用秘钥 (如果不配置则使用全局默认秘钥)
                secretKey: SSO-C3-kQwIOrYvnXmSDkwEiFngrKidMcdrgKor

sa-token.dao: #名字可以随意取
    redis:
        server: "localhost:6379"
#        password: 123456
        db: 1
        maxTotal: 200


    
        