# 端口
server:
    port: 9001

# Sa-Token 配置 
sa-token:
    # 打印操作日志
    is-log: true

    # SSO-相关配置
    sso-client:
        # client 标识
        client: sso-client1
        # SSO-Server端 - 主机地址
        server-url: http://sso.stp.com:9000
    
# 配置 Sa-Token 单独使用的Redis连接 （此处需要和SSO-Server端连接同一个Redis）
sa-token.dao: #名字可以随意取
    redis:
        server: "localhost:6379"
#        password: 123456
        db: 1
        maxTotal: 200
        
        
        
        
        